// data.js — Yumlog seed data & rank definitions

const RANKS = [
  { id: 'rookie',     name: 'Rookie Noodle',      emoji: '🍜', minPts: 0,    maxPts: 199,      weight: 0.5  },
  { id: 'corporal',   name: 'Corporal Cupcake',   emoji: '🧁', minPts: 200,  maxPts: 499,      weight: 0.75 },
  { id: 'lieutenant', name: 'Lieutenant Lasagna', emoji: '🍝', minPts: 500,  maxPts: 799,      weight: 0.9  },
  { id: 'captain',    name: 'Captain Croissant',  emoji: '🥐', minPts: 800,  maxPts: 1199,     weight: 1.1  },
  { id: 'major',      name: 'Major Meatball',     emoji: '🍖', minPts: 1200, maxPts: 1999,     weight: 1.2  },
  { id: 'commander',  name: 'Commander in Beef',  emoji: '🥩', minPts: 2000, maxPts: 4999,     weight: 1.3  },
  { id: 'fivestar',   name: 'Five-Star Foodie',   emoji: '⭐', minPts: 5000, maxPts: Infinity, weight: 1.5  },
];

// Points awarded per action
const POINTS = {
  quickReview:  5,
  blogPost:     15,
  helpfulVote:  2,   // awarded to the review author
  honestVote:   2,
};

const SEED_USERS = [
  {
    id: 'u1',
    name: 'Emma Thompson',
    initials: 'ET',
    email: 'emma@example.com',
    password: 'demo',
    points: 5234,
    location: 'Sydney, NSW',
    memberSince: '2023-01',
    bio: 'Professional food critic and travel writer. I visit each restaurant multiple times before writing a review.',
    followers: 1543,
    following: 89,
    avatarGradient: 'linear-gradient(135deg,#9C27B0,#E91E63)',
  },
  {
    id: 'u2',
    name: 'Mike Rodriguez',
    initials: 'MR',
    email: 'mike@example.com',
    password: 'demo',
    points: 2156,
    location: 'Sydney, NSW',
    memberSince: '2023-03',
    bio: "BBQ master and meat lover. If it's grilled, smoked or slow-cooked, I've tried it.",
    followers: 892,
    following: 134,
    avatarGradient: 'linear-gradient(135deg,#F4622A,#F9A825)',
  },
  {
    id: 'u3',
    name: 'Sarah Chen',
    initials: 'SC',
    email: 'sarah@example.com',
    password: 'demo',
    points: 847,
    location: 'Sydney, NSW',
    memberSince: '2024-01',
    bio: "Coffee enthusiast ☕ and pasta lover 🍝 exploring Sydney's food scene one meal at a time.",
    followers: 234,
    following: 189,
    avatarGradient: 'linear-gradient(135deg,#E63946,#F4622A)',
  },
  {
    id: 'u4',
    name: 'James Liu',
    initials: 'JL',
    email: 'james@example.com',
    password: 'demo',
    points: 612,
    location: 'Sydney, NSW',
    memberSince: '2023-11',
    bio: "Italian food obsessive. I've eaten pasta in 15 countries and counting.",
    followers: 178,
    following: 201,
    avatarGradient: 'linear-gradient(135deg,#c0392b,#e67e22)',
  },
  {
    id: 'u5',
    name: 'Aiko Kobayashi',
    initials: 'AK',
    email: 'aiko@example.com',
    password: 'demo',
    points: 203,
    location: 'Sydney, NSW',
    memberSince: '2024-06',
    bio: 'Japanese-Australian foodie. Love finding authentic Asian cuisine hidden in Sydney.',
    followers: 45,
    following: 78,
    avatarGradient: 'linear-gradient(135deg,#d35400,#f39c12)',
  },
];

const SEED_RESTAURANTS = [
  {
    id: 'r1',
    name: 'Bella Vita Trattoria',
    emoji: '🍝',
    cuisine: 'italian',
    priceRange: '$$$',
    address: '123 Crown Street',
    suburb: 'Sydney CBD',
    distance: 0.3,
    phone: '(02) 9876 5432',
    website: 'bellavita.com.au',
    description: 'Bella Vita Trattoria brings authentic Italian flavors to the heart of Sydney. Our family recipes have been passed down through three generations, and we take pride in making everything from scratch daily — from our hand-rolled pasta to our house-made tiramisu.',
    hours: { monday: null, tuesday: '17:30–22:00', wednesday: '17:30–22:00', thursday: '17:30–22:00', friday: '17:30–23:00', saturday: '12:00–23:00', sunday: '12:00–21:00' },
    amenities: ['Outdoor seating', 'Wheelchair accessible', 'Takeaway', 'Reservations', 'Wine bar'],
    imgGradient: 'linear-gradient(135deg,#ffe0b2,#ffcc80)',
    badges: ['⭐ Top Rated'],
    openNow: true,
    parking: false,
    wheelchairAccessible: true,
  },
  {
    id: 'r2',
    name: 'Tokyo Ramen House',
    emoji: '🍜',
    cuisine: 'japanese',
    priceRange: '$$',
    address: '45 King Street',
    suburb: 'Newtown',
    distance: 0.5,
    phone: '(02) 9555 1234',
    website: 'tokyoramen.com.au',
    description: 'Authentic tonkotsu ramen broth simmered for 18 hours. The taste of Tokyo in the heart of Sydney.',
    hours: { monday: '11:00–22:00', tuesday: '11:00–22:00', wednesday: '11:00–22:00', thursday: '11:00–22:00', friday: '11:00–23:00', saturday: '11:00–23:00', sunday: '11:00–21:00' },
    amenities: ['Takeaway', 'Wheelchair accessible'],
    imgGradient: 'linear-gradient(135deg,#e3f2fd,#bbdefb)',
    badges: [],
    openNow: true,
    parking: false,
    wheelchairAccessible: true,
  },
  {
    id: 'r3',
    name: 'The Burger Spot',
    emoji: '🍔',
    cuisine: 'american',
    priceRange: '$',
    address: '78 Pitt Street',
    suburb: 'Sydney CBD',
    distance: 0.7,
    phone: '(02) 9333 5678',
    website: 'theburgerspot.com.au',
    description: 'Fresh, never-frozen smash burgers made to order. Simple done right.',
    hours: { monday: '11:00–22:00', tuesday: '11:00–22:00', wednesday: '11:00–22:00', thursday: '11:00–22:00', friday: '11:00–23:00', saturday: '12:00–23:00', sunday: '12:00–21:00' },
    amenities: ['Takeaway', 'Parking available'],
    imgGradient: 'linear-gradient(135deg,#fce4ec,#f8bbd0)',
    badges: ['🆕 New'],
    openNow: true,
    parking: true,
    wheelchairAccessible: false,
  },
  {
    id: 'r4',
    name: 'Green Leaf Cafe',
    emoji: '🥗',
    cuisine: 'vegan',
    priceRange: '$$',
    address: '22 Crown Street',
    suburb: 'Surry Hills',
    distance: 0.9,
    phone: '(02) 9222 9876',
    website: 'greenleaf.com.au',
    description: "Plant-based dining that doesn't compromise on flavour. Creative vegan dishes for everyone.",
    hours: { monday: '08:00–16:00', tuesday: '08:00–16:00', wednesday: '08:00–16:00', thursday: '08:00–16:00', friday: '08:00–17:00', saturday: '09:00–17:00', sunday: '09:00–15:00' },
    amenities: ['Outdoor seating', 'Wheelchair accessible', 'Takeaway'],
    imgGradient: 'linear-gradient(135deg,#e8f5e9,#c8e6c9)',
    badges: [],
    openNow: true,
    parking: false,
    wheelchairAccessible: true,
  },
  {
    id: 'r5',
    name: 'Napoli Pizza & Pasta',
    emoji: '🍕',
    cuisine: 'italian',
    priceRange: '$$',
    address: '56 George Street',
    suburb: 'Sydney CBD',
    distance: 0.8,
    phone: '(02) 9444 3210',
    website: 'napolipizza.com.au',
    description: 'Wood-fired Neapolitan pizza and fresh pasta. Simple, honest, delicious.',
    hours: { monday: '11:30–22:00', tuesday: '11:30–22:00', wednesday: '11:30–22:00', thursday: '11:30–22:00', friday: '11:30–23:00', saturday: '12:00–23:00', sunday: '12:00–21:00' },
    amenities: ['Takeaway', 'Parking available', 'Wheelchair accessible'],
    imgGradient: 'linear-gradient(135deg,#ffebee,#ffcdd2)',
    badges: [],
    openNow: true,
    parking: true,
    wheelchairAccessible: true,
  },
  {
    id: 'r6',
    name: 'Osteria Moderna',
    emoji: '🥘',
    cuisine: 'italian',
    priceRange: '$$$$',
    address: '88 Macquarie Street',
    suburb: 'Sydney CBD',
    distance: 1.2,
    phone: '(02) 9111 2222',
    website: 'osteriamoderna.com.au',
    description: 'Contemporary Italian fine dining. Seasonal menus celebrating the finest local produce.',
    hours: { monday: null, tuesday: null, wednesday: '18:00–22:00', thursday: '18:00–22:00', friday: '18:00–23:00', saturday: '12:00–15:00 & 18:00–23:00', sunday: '12:00–15:00' },
    amenities: ['Reservations required', 'Wheelchair accessible', 'Wine bar', 'Private dining'],
    imgGradient: 'linear-gradient(135deg,#fff3e0,#ffe0b2)',
    badges: [],
    openNow: false,
    parking: false,
    wheelchairAccessible: true,
  },
  {
    id: 'r7',
    name: 'La Piccola Italia',
    emoji: '🌿',
    cuisine: 'italian',
    priceRange: '$$$',
    address: '14 Riley Street',
    suburb: 'Darlinghurst',
    distance: 1.5,
    phone: '(02) 9888 4321',
    website: 'lapiccolaitalia.com.au',
    description: 'Intimate neighbourhood Italian restaurant with a focus on seasonal, locally sourced ingredients.',
    hours: { monday: null, tuesday: '18:00–22:00', wednesday: '18:00–22:00', thursday: '18:00–22:00', friday: '18:00–23:00', saturday: '12:00–23:00', sunday: '12:00–21:00' },
    amenities: ['Outdoor seating', 'Wheelchair accessible', 'Reservations'],
    imgGradient: 'linear-gradient(135deg,#e8f5e9,#c8e6c9)',
    badges: [],
    openNow: true,
    parking: false,
    wheelchairAccessible: true,
  },
  {
    id: 'r8',
    name: 'Trattoria del Porto',
    emoji: '🍷',
    cuisine: 'italian',
    priceRange: '$$$',
    address: '5 Circular Quay West',
    suburb: 'The Rocks',
    distance: 2.1,
    phone: '(02) 9777 8888',
    website: 'trattoriadelporto.com.au',
    description: 'Waterfront Italian dining with stunning harbour views. Seafood pasta is the house specialty.',
    hours: { monday: '12:00–22:00', tuesday: '12:00–22:00', wednesday: '12:00–22:00', thursday: '12:00–22:00', friday: '12:00–23:00', saturday: '12:00–23:00', sunday: '12:00–21:00' },
    amenities: ['Outdoor seating', 'Wheelchair accessible', 'Parking available', 'Wine bar', 'Reservations'],
    imgGradient: 'linear-gradient(135deg,#fce4ec,#f8bbd0)',
    badges: [],
    openNow: true,
    parking: true,
    wheelchairAccessible: true,
  },
];

const now = Date.now();
const day = 86400000;

const SEED_REVIEWS = [
  {
    id: 'rv1',
    restaurantId: 'r1',
    userId: 'u3',
    rating: 5,
    text: 'Absolutely incredible pasta carbonara! The guanciale was perfectly crispy and the egg sauce was silky smooth. This is hands down the best Italian in the city. The tiramisu is also a must-try — they make it fresh daily and you can really taste the difference.',
    type: 'quick',
    photos: ['🍝', '🍰', '🥗'],
    helpfulVotes: 45,
    honestVotes: 38,
    replies: 3,
    date: new Date(now - 2 * day).toISOString(),
  },
  {
    id: 'rv2',
    restaurantId: 'r1',
    userId: 'u2',
    rating: 4,
    text: 'Great food but service was a bit slow on a Saturday night. The risotto was outstanding though — creamy and perfectly cooked with just the right amount of parmesan. Prices are reasonable for the quality. Would definitely come back but maybe on a quieter night.',
    type: 'quick',
    photos: ['🥘', '🍷'],
    helpfulVotes: 32,
    honestVotes: 29,
    replies: 0,
    date: new Date(now - 7 * day).toISOString(),
  },
  {
    id: 'rv3',
    restaurantId: 'r1',
    userId: 'u1',
    rating: 5,
    blogTitle: 'A Deep Dive into Bella Vita: Traditional Meets Modern',
    text: 'After visiting three times over the past month, I wanted to share a comprehensive review. The ambiance strikes a perfect balance between rustic Italian charm and contemporary elegance. Their hand-made pasta is genuinely extraordinary — you can taste the difference in every bite. The chef\'s attention to detail is evident in everything from the carefully sourced ingredients to the beautiful presentation.',
    type: 'blog',
    photos: [],
    helpfulVotes: 156,
    honestVotes: 142,
    replies: 8,
    date: new Date(now - 14 * day).toISOString(),
  },
  {
    id: 'rv4',
    restaurantId: 'r2',
    userId: 'u3',
    rating: 5,
    blogTitle: 'Ramen Perfection: Why Tokyo Ramen House is Worth the Queue',
    text: "After trying every ramen spot in Sydney, I've finally found the one that rivals what I ate in Tokyo. The tonkotsu broth is simmered for 18 hours, and you can taste every minute of that dedication. The noodles have that perfect al dente bite, and the chashu pork just melts.",
    type: 'blog',
    photos: ['🍜', '🥚', '🌿', '🍷', '🥢', '🍱'],
    helpfulVotes: 112,
    honestVotes: 98,
    replies: 15,
    date: new Date(now - 7 * day).toISOString(),
  },
  {
    id: 'rv5',
    restaurantId: 'r4',
    userId: 'u3',
    rating: 4,
    text: 'Beautiful vegan cafe with creative dishes. The jackfruit burger was surprisingly meaty and flavorful. Slightly pricey but portions are generous. Great spot for a healthy lunch!',
    type: 'quick',
    photos: ['🥗', '🍔'],
    helpfulVotes: 28,
    honestVotes: 24,
    replies: 2,
    date: new Date(now - 14 * day).toISOString(),
  },
  {
    id: 'rv6',
    restaurantId: 'r5',
    userId: 'u1',
    rating: 5,
    text: 'Best Neapolitan pizza in Sydney. The wood-fired oven gives the crust a perfect char while keeping the centre soft and chewy. Their margherita with buffalo mozzarella is a masterpiece.',
    type: 'quick',
    photos: ['🍕'],
    helpfulVotes: 89,
    honestVotes: 76,
    replies: 5,
    date: new Date(now - 21 * day).toISOString(),
  },
  {
    id: 'rv7',
    restaurantId: 'r2',
    userId: 'u2',
    rating: 5,
    text: 'The karaage chicken add-on is an absolute game-changer. Order the spicy miso ramen with extra chashu pork. You will not regret it.',
    type: 'quick',
    photos: ['🍜'],
    helpfulVotes: 41,
    honestVotes: 38,
    replies: 2,
    date: new Date(now - 3 * day).toISOString(),
  },
  {
    id: 'rv8',
    restaurantId: 'r3',
    userId: 'u4',
    rating: 4,
    text: "Solid smash burgers at a great price. The double patty with special sauce is the move. Fries are crispy and well-seasoned. Nothing fancy but exactly what you want from a burger joint.",
    type: 'quick',
    photos: ['🍔', '🍟'],
    helpfulVotes: 19,
    honestVotes: 17,
    replies: 1,
    date: new Date(now - 5 * day).toISOString(),
  },
  {
    id: 'rv9',
    restaurantId: 'r5',
    userId: 'u4',
    rating: 5,
    text: 'The cacio e pepe is a revelation. So simple, yet so perfectly executed. This is the Italian I grew up eating. Thank you Napoli Pizza!',
    type: 'quick',
    photos: ['🍝'],
    helpfulVotes: 33,
    honestVotes: 31,
    replies: 0,
    date: new Date(now - 10 * day).toISOString(),
  },
  {
    id: 'rv10',
    restaurantId: 'r8',
    userId: 'u1',
    rating: 4,
    text: 'Gorgeous setting on the harbour. The seafood linguine was excellent — generous portions of prawns and clams in a rich bisque sauce. Service was attentive without being overbearing. A little pricey but worth it for a special occasion.',
    type: 'quick',
    photos: ['🍝', '🦐'],
    helpfulVotes: 67,
    honestVotes: 58,
    replies: 4,
    date: new Date(now - 4 * day).toISOString(),
  },
];
